name: Upload Atrifacts 
on: 
  push:
    branches:
     [main]
jobs:
  test: 
   runs-on: ubuntu-latest
   steps:
    - name: Get Code
      uses: actions/checkout@v4
    - name: Install dependencies
      run: npm ci
    - run: npm init @eslint/config
    - name: Lint code
      run: npm run lint
    - name: Test code
      run: npm run test
  build: 
    needs: test
    runs-on: ubuntu-latest
    steps: 
      - name: Get Code
        uses: actions/checkout@v4
      - name: Install dependencies
        run: npm ci
      - name: build app
        run: npm run build
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        run: echo "Deploying ..."




      
